name: customer
description: JAJ Net ISP Customer App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.1.2
  pdf: ^3.10.7
  share_plus: ^7.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/HindSiliguri-Regular.ttf
    - assets/fonts/HindSiliguri-Bold.ttf
    - assets/fonts/HindSiliguri-SemiBold.ttf
    - assets/fonts/NotoSansBengali-Regular.ttf
    - assets/fonts/NotoSansBengali-Bold.ttf
